version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: exam-vault-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./schedules.json:/usr/src/app/schedules.json
